### ISSUE TITLE
Vgate iCar 2 Wifi disable sleep mode?

### ISSUE THREAD

**Issue by hassehaka** [dconlon/icar_odb_wifi#2]
I have the above mentioned adapter (not the Pro model).

It uses a different wifi chip which appears to be the USR-C216 [https://www.pusr.com/download/WIFI/USR-C216-User-Manual-V1.0.0.pdf](url)

The wifi settings of the chip can easily be changed to STA mode etc through a web interface at 192.168.0.10 when you connect to it using login/pass admin/admin.

The problem I have is that I cannot disable the sleep function which means that the chip shuts down when my car is not within the range of my wifi.

It supports AT commands as well but I did not find anything related to the sleep function.
[https://www.pusr.com/download/WIFI/USR-C216-AT-commands-V1.0.0.pdf](url)

Anyone who knows how to disable sleep?

**Comment by dconlon** [comment]
On my iCar 2, which is obviously using a different WiFi chip to yours, it was the low power function of the ELM being used to shutdown the WiFi after a period of inactivity.  Disabling the low power function of the ELM solved the issue for me.  Have you tried this:

https://github.com/dconlon/icar_odb_wifi/blob/main/src/disable_low_power_mode.py

**Comment by hassehaka** [comment]
I somehow overlooked this before and did not realize the role of the ELM. It was the missing piece and sending sending the messages you linked to solved the problem. Thanks !
